name: Daily Database Backup

# auto-trigger workflow when push to main branch or on a schedule (every day at midnight)
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Backup File with Timestamp using Docker
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          # 1. create a timestamp in the format YYYY-MM-DD_HH-MM (e.g., 2026-02-21_07-00)
          TIMESTAMP=$(date -u -d "+7 hours" +'%Y-%m-%d_%H-%M')
          
          # 2. make a new filename with that timestamp
          FILENAME="backup_database_TinViet_${TIMESTAMP}.sql"
          
          # 3. use Docker to run pg_dump and save the output to the file
          docker run --rm postgres:17 pg_dump "$DATABASE_URL" > "$FILENAME"
          
          echo "âœ… Created backup file: $FILENAME"

      - name: Upload Backup to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          # name of the artifact in GitHub
          name: db-backup-${{ github.sha }}
          
          # Must use * to match the filename with the timestamp
          path: backup_database_TinViet_*.sql
          
          retention-days: 30